### PR TITLE
fixed symbolics proc resolution

### PR DESCRIPTION
**Pull request by jangko**
I found a minor bug and fixed it
also add some test

### CODE REVIEW

**Comment by jangko** [comment]
the C backend test seems ok, but the JS one failed, any idea whats wrong here?

**Comment by yglukhov** [comment]
Well, the `malt` value constraint is underdefined, and it actually satisfies the constraints in the end. So technically the test is a bit incorrect. But yeah, I would definitely expect JS to work the same way as C, and I've got no idea why it's different %).

**Comment by jangko** [comment]
the C version, malt.value = 980
the JS version, malt.value = 1190

the old kiwi C++ also exhibit this behavior(same as JS one)
your kiwi produce the same result with java cassowary

**Comment by yglukhov** [comment]
Ok, for now I think that the test should be updated to not rely on `980`. Of course, you're always welcome to look into this "reproducibility" issue, if you've got mood for it.

**Comment by jangko** [comment]
actually, I have a very strong desire to know why this behavior occurs.
when I ported java-cassowary to nim, the difference between java-hashmap vs nim-table[k,v] and java-hashset vs nim-hashset proved to be the source of many headaches.

I don't know how nim-js-codegen translate Table[k,v] into it's js counterpart.
simplex-solver seems affected by the stability of the hash-function of a hash-map.
when the algorithm iterate over the hash-map elements, different order could yield different result.

something like `for k,v in some_hashmap:` on different [language/implementation/hash-function] can have different order of iteration between runtime execution, although the input dataset is same.

perhaps you can confirm my suspicion, either right or wrong.

**Comment by yglukhov** [comment]
@jangko, in such case you might want to know that `kiwi` implements `hash` function by casting refs to ints, and js version assigns "unique" ids to the objects and treats them as hash value. If solver algorithm depends on table stability as you are stating, then these hashing technique is definitely a place to look into.

**Comment by yglukhov** [comment]
Thinking a bit more about it, it looks impossible to make the system stable. In case of underdefined constraints how can you decide which of many variables has to be changed? Even if you're relying on the order of solver configuration this will work only in simple tests. In real life the solver will likely be configured in a more complex manner with logic scattered across many functions/modules/etc. So once again I tend to conclude that reproducible result with underdefined constraints is not worth pursuing.

**Comment by jangko** [comment]
indeed the hash-function it the one who cause the different result between C and JS.
when I altered the code a bit, and assign unique id to hashed ref object for C backend, both version now produce the same result.
thank you very much for your hint.
I already updated the test.

**Pull request merged**
